### ISSUE TITLE
[FEATURE] Make forbiddenfruit optional

### ISSUE THREAD

**Issue by m-doescode** [didactic-meme/pyfuncol#27]
It would be great if forbiddenfruit was made optional. Since forbiddenfruit requires CPython and I think if it would be better if it could work on other versions of python.

Instead of:
```py
import pyfuncol

my_list = [1, 2, 3]
print(my_list.map(lambda x: x * 2))
```
I can do:
```py
from pyfuncol.list import *

my_list = [1, 2, 3]
print(map(my_list, lambda x: x * 2))
```

Maybe there can be a check to see if forbiddenfruit is installed. If it is, add all the functions to the builtin classes, otherwise do nothing.

Sorry if I misunderstand how this works.

**Comment by Gondolav** [comment]
Hi! The library's primary goal is to offer extension functions, but indeed what you're suggesting can be useful and easily added, I think.

The best way to do so would be to move all forbiddenfruit related code to the `__init__.py`, maybe add a check to see if the library is installed (not sure it's needed) and then provide an "extra" when installing via pip that doesn't install forbiddenfruit, something like "pip install pyfuncol[pure]".

In this way, your second example should run without problems.

What do you think? Would you be interested in helping with such a feature?

**Comment by m-doescode** [comment]
Sure! Why not?

I'm not sure how to create a seperate pure version because I'm not very familiar with pip publishing, but I can definitely help with refactoring the code so forbiddenfruit is optional

**Comment by Gondolav** [comment]
That's great, we can handle pip if you want!

**Comment by Gondolav** [comment]
A small update. Extras can only install additional packages, so the only modifications to do apart from moving the code is the import check as we were discussing, something like:

```python
try:
  from forbiddenfruit import curse
except ImportError:
  <maybe print a warning?>
```

This however means that users will also install forbiddenfruit by default when installing pyfuncol.
